spring:
  datasource:
    url: jdbc:mysql://localhost:3306/subject
    username: root
    password: Trang@12345

  liquibase:
    change-log: classpath:migration/master-changelog.xml

  application:
    name: subject-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

  application:
    name: subject-service  # Tên của dịch vụ khi đăng ký với Eureka
  cloud:
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/  # Địa chỉ Eureka Server
      instance:
        prefer-ip-address: true  # Sử dụng địa chỉ IP thay vì hostname

server:
  port: 8088
