spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    change-log: classpath:migration/master-changelog.xml

  application:
    name: subject-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

  application:
    name: subject-service
  cloud:
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true

server:
  port: 8088

Secret: ${JWT_SECRET}

subject:
  service:
    url: http://SUBJECT-SERVICE/api/v1/subjects

lecturer:
  service:
    url: http://LECTURER-SERVICE/api/v1/lecturers
department:
  service:
    url: http://DEPARTMENT-SERVICE/api/v1/departments


