server:
  port: 8080

spring:
  application:
    name: api-gateway

  main:
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      routes:
        - id: course-service-route
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/api/v1/courses
          filters:
            - StripPrefix=2
        - id: student-service-route
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api/v1/students
          filters:
            - StripPrefix=2
        - id: attendance-service-route
          uri: lb://ATTENDANCE-SERVICE
          predicates:
            - Path=/api/v1/attendances
          filters:
            - StripPrefix=2
        - id: grade-service-route
          uri: lb://GRADE-SERVICE
          predicates:
            - Path=/api/v1/grades
          filters:
            - StripPrefix=2
        - id: subject-service-route
          uri: lb://SUBJECT-SERVICE
          predicates:
            - Path=/api/v1/subjects
          filters:
            - StripPrefix=2
        - id: lecturer-service-route
          uri: lb://LECTURER-SERVICE
          predicates:
            - Path=/api/v1/lecturers
          filters:
            - StripPrefix=2
        - id: class-service-route
          uri: lb://CLASS-SERVICE
          predicates:
            - Path=/api/v1/classes
          filters:
            - StripPrefix=2
        - id: department-service-route
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/v1/departments
          filters:
            - StripPrefix=2
        - id: studentcourse-service-route
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/api/v1/studentcourses
          filters:
            - StripPrefix=2
        - id: subjectlecturer-service-route
          uri: lb://SUBJECT-SERVICE
          predicates:
            - Path=/api/v1/subjectlecturers
          filters:
            - StripPrefix=2
        - id: auth-service-login-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/users/login
          filters:
            - StripPrefix=2
        - id: auth-service-register-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/users/register/**
          filters:
            - StripPrefix=2
        - id: auth-service-verify-token-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/users/verify-token
          filters:
            - StripPrefix=2
        - id: auth-service-logout
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/users/logout
          filters:
            - StripPrefix=2

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true


secret: ${JWT_SECRET}
