spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    change-log: classpath:migration/master-changelog.xml

  application:
    name: grade-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

  application:
    name: grade-service
  cloud:
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true

server:
  port: 8085

Secret: ${JWT_SECRET}

student:
  service:
    url: http://STUDENT-SERVICE/api/v1/students

course:
  service:
    url: http://COURSE-SERVICE/api/v1/courses


