spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/error_messages
    encoding: UTF-8
  liquibase:
    change-log: classpath:migration/master-changelog.xml

  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

  application:
    name: auth-service
  cloud:
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true

server:
  port: 8089

Secret: ${JWT_SECRET}

expirationMs: 3600000000 # 1 hour
refreshExpirationMs: 86400000 # 24 hours
