spring:
  datasource:

    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: Trang@12345
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/error_messages
    encoding: UTF-8
  liquibase:
    change-log: classpath:migration/master-changelog.xml

  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

  application:
    name: auth-service  # Tên của dịch vụ khi đăng ký với Eureka
  cloud:
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/  # Địa chỉ Eureka Server
      instance:
        prefer-ip-address: true  # Sử dụng địa chỉ IP thay vì hostname

server:
  port: 8089


Secret: 03295e54e2aa5f1f5ca7bc3762f3a35684ae625d64cc644534e2ce8504a46539

expirationMs: 3600000000 # 1 hour
refreshExpirationMs: 86400000 # 24 hours
#jwtSecret: ZFDF8GJS4ADFA64ASDeimY