spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  application:
    name: attendance-service

  liquibase:
    change-log: classpath:migration/master-changelog.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

  application:
    name: student-service
  cloud:
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true

server:
  port: 8081

Secret: ${JWT_SECRET}

course:
  service:
    url: http://COURSE-SERVICE/api/v1/courses

student:
  service:
    url: http://STUDENT-SERVICE/api/v1/students



