spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:migration/master-changelog.xml
  application:
    name: student-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

  application:
    name: student-service
  cloud:
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true

server:
  port: 8087


Secret: ${JWT_SECRET}
class:
  service:
    url: http://localhost:8089/api/v1/classes
