
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: Trang@12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:migration/master-changelog.xml
  application:
    name: student-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

  application:
    name: student-service
  cloud:
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true

server:
  port: 8087


Secret: 03295e54e2aa5f1f5ca7bc3762f3a35684ae625d64cc644534e2ce8504a46539
class:
  service:
    url=http://localhost:8089/api/v1/classes: